import Early from "@/components/Landing/Early";
import Faq from "@/components/Landing/Faq";
import Hero from "@/components/Landing/Hero";
import MobileApp from "@/components/Landing/MobileApp";
import Partners from "@/components/Landing/Partners";
import Press from "@/components/Landing/Press";
import Project from "@/components/Landing/Project";
import Releases from "@/components/Landing/Releases";
import Share from "@/components/Landing/Share";
import Steps from "@/components/Landing/Steps";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Early />
      <Releases />
      <Partners />
      <Share />
      <Steps />
      <Project />
      <Press />
      <Faq />
      <MobileApp />
    </>
  );
}
